version: "2"

services:
  namenode:
    image: bde2020/hadoop-namenode:1.0.0-hadoop2.7.1
    container_name: namenode
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "50070:50070"
      - "8020:8020"
    
  datanode:
    image: bde2020/hadoop-datanode:1.0.0-hadoop2.7.1
    container_name: datanode
    volumes:
      - ./data/datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env

  datanode1:
    image: bde2020/hadoop-datanode:1.0.0-hadoop2.7.1
    container_name: datanode1
    volumes:
      - ./data/datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env


   
   




  hive-server:
    build: .
    container_name: hive-server
    env_file:
      - ./hadoop-hive.env
    environment:
      - "HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore/metastore"
    links:
      - "hive-metastore"
      - "namenode"
    ports:
      - "10000:10000"






  hive-metastore:
    build: .
    container_name: hive-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.1.0


  hue:
    image: gethue/hue
    hostname: hue
    container_name: hue
    domainname: dockerhive_default
    networks:
      - dockerhive_default
    environment:
      - NAMENODE_HOST=namenode
    ports:
      - "8088:8888"
    env_file:
      - ./hadoop.env
    volumes:
      - ./hue-conf:/hue/desktop/conf




networks:
  dockerhive_default:
    external: true
